# Generated by Django 3.2.7 on 2021-09-25 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sidekicks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sidekicks',
            new_name='Sidekick',
        ),
    ]
