# Generated by Django 3.2.7 on 2021-09-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='description',
            field=models.CharField(default='none', max_length=750),
            preserve_default=False,
        ),
    ]
